In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
cv = CountVectorizer()

In [3]:
text = ['london paris london','paris london paris','paris london america']
count_matrix = cv.fit_transform(text)
similarity_score = cosine_similarity(count_matrix)
print(count_matrix.toarray())
print(similarity_score)

[[0 2 1]
 [0 1 2]
 [1 1 1]]
[[1.         0.8        0.77459667]
 [0.8        1.         0.77459667]
 [0.77459667 0.77459667 1.        ]]


Read the data

In [2]:
df = pd.read_csv('IMDB-Movie-Data.csv')

In [3]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [10]:
df['Title'].unique

<bound method Series.unique of 0      Guardians of the Galaxy
1                   Prometheus
2                        Split
3                         Sing
4                Suicide Squad
                ...           
995       Secret in Their Eyes
996            Hostel: Part II
997     Step Up 2: The Streets
998               Search Party
999                 Nine Lives
Name: Title, Length: 1000, dtype: object>

In [1]:
def movie_recommendations(movie_user_likes):
    
    import numpy as np
    import pandas as pd
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    
    df = pd.read_csv('IMDB-Movie-Data.csv')
    
    #feature selection
    feature = ['Title','Genre','Director','Actors']

     #Creating a column which can combine all the selected features.
    def combine_features(row):
        return row['Title'] + " "+row['Genre'] +" "+ row['Director'] +" "+ row['Actors']
    #applying this method into our dataset
    df['Combine'] = df.apply(combine_features,axis = 1)

    #creating the count matrix from new combine features.
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(df['Combine'])

    #getting the cosine similarity in the count matrix.
    cosine_sim =  cosine_similarity(count_matrix)

    #to give similar movies we need the index of the movie.We can have bu seeing the rank features.
    def get_index_from_title(title):
        return df[df.Title == title]['Rank'].values[0]

    #getting the index of that movie
    movie_index = get_index_from_title(movie_user_likes)##

    #enumerate the list 
    similar_movies = list(enumerate(cosine_sim[movie_index]))

    #sorting the list of tupples in descending order.
    sorted_similar_movies = sorted(similar_movies,key = lambda x:x[1], reverse = True)

    #function for getting the title of the similar movie from index
    def get_index_from_title(index):
        return df[df.Rank == index]['Title'].values[0]

    #loop for printing similar movie
    i = 0
    for movie in sorted_similar_movies:
        print(get_index_from_title(movie[0]))
        i = i+1
        if i>10:
            break

In [2]:
x = 'Why Him?'
movie_recommendations('Why Him?')

Why Him?
City of Tiny Lights
Legion
The Girl on the Train
Spectre
Lion
L'avenir
The Exception
Hush
Their Finest
What We Do in the Shadows
